// ≺⧼ Tradukoj — la aiha lingvo 🗣️ ⧽≻
// La aih-aj ( Gawekiif ) tekstoj de la tuta interfaco. La vortaro estas
// nur datumoj — la traduk-funkcioj, la lingvo-sxaltado kaj la
// DOM-aplikado restas en kantaoj/lingvo/tradukoj.ts.
// La aih-aj formoj estas la FONTO de la derivitaj nomoj ( la sonaj reguloj ).

export const AIH: Record<string, string> = {
  // Adjektivoj iras ANTAŬ la substantivo por priskriboj ( Iikrhia gramatika regulo ).
  // to signal a fused compound name rather than a mere description.
  "titoloAranis": "ꞁȷ̀ᴜƣ̋ ꞁȷ̀ᴜ }ʃꞇɔ˞",
  "subtitoloUrbo": "j͐ʃɜ ɭʃᴜ ꞁȷ̀ɹ ֭ſɭɹɔ˞ • j͐ʃᴜ ŋᷠɹⰱ ꞁȷ̀ᴜꞇ ſɭᴜ ɭl̀ɹ ɭʃɔ",
  "eniri": "ſɭw ſ̀ȷᴜ",
  "butonoPromeni": "ſɭᴜ ɭʃᴜ",
  "butonoOrbiti": "֭ſɭɹ j͑ʃɔ",
  "butonoVestaro": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜ j͑ʃɜȝ ɭʃɔ",
  "butonoHelpo": "ſȷɔ ſɭ,ꞇ",
  "titoloTeksilo": "ſɟᴜ j͑ʃ'ᴜ ı],ͷ̗ɔʞ",
  "subtitoloTeksilo": "j͑ʃᴜ ֭ſɭᴜƽ ʌ ſɭ,ɹ ſ̀ȷɔ • ſɟɹ }ʃᴜ ʌ ɭʃᴜ ŋᷠᴜ v j͑ʃɜȝ ɭʃɔ j͑ʃᴜꞇ • ſ͔ɭɔ j͐ʃɔɔ˞ ʌ ᶅſɔ ֭ſɭɹ ｡ ɭʃɜƽ v ֭ſɭᴜ ı],ɔ j͑ʃᴜꞇ",
  "titoloSxargxo": "ꞁȷ̀ᴜƣ̋ ꞁȷ̀ᴜ }ʃꞇɔ˞",
  "sxargxaSubskribo": "ſɭᶗ‹ɔ ʌ j͑ʃ'ɔ ſןᴜȝ",
  "sxargxaSatalo": "j͑ʃ'ɔ ſןᴜȝ ʌ j͑ʃᴜ ɭʃᴜͷ̗ ⟅",
  "sxargxaTraboj": "ı],ɔ ŋᷠᴜ ʌ ſɭᴜc̗ ɭʃɜ }ʃꞇ ⟅",
  "sxargxaNebulo": "j͐ʃᴜɔ˞ ʌ j͐ʃɜ ɭʃᴜ ʌ ⺓ ʌ ŋᷠᴜ ֭ſɭᴜ ⟅",
  "kompasoNordo": "j͐ʃᴜȝ",
  "regiloOrbito": "֭ſɭɹ j͑ʃɔ • ſɭc̗ᴜ ʃэ ɭʃɔȝ • ſןɔ ʌ ʃэ ɭʃɔȝ",
  "regiloPromeno": "ſɭᴜ ɭʃᴜ • WASD • Shift ſɭᴜ ſɭʞᴜȝ • Spaco ſןw",
  "regiloMovado": "WASD • ſɭᴜ ſɭʞᴜȝ ſɭc̭ᴜ ſɭc̗w",
  "regiloEniri": "E • ſɭw ſ̀ȷᴜ / j͑ʃwc̗ ɭʃᴜ • ſɭw ſ̀ȷᴜ ſɭэ ſɭᴜ ſɭw ʃᴜ",
  "regiloMapo": "M • ſɟᴜ ſᶘɹ }ʃᴜ j͑ʃᴜ ſɭᴜ ſɭw ʃᴜ ſɭэ",
  "regiloEliri": "Esc • j͑ʃwc̗ ɭʃᴜ",
  "regiloSpajroj": "ſןɔ ʌ ſ͕ɭᴜ ʌ ſɭɔ ʌ ʃэ ſɭɔ˞ᴜ ʌ ſɭᴜ ʌ ꞁȷ̀ɹ ʃᴜ • ſɭw ſ̀ȷᴜ",
  "regiloVesto": "ſ̀ȷᴜȝ • ſ̀ȷᴜȝ ſɭw ſ̀ȷᴜ",
  "titoloVojoj": "ſɭэ ֭ſɭэ",
  "subtitoloHelpo": "ſȷɔ ſɭ,ꞇ ʌ ſɭэ ʌ ſɭᴜ ſɭɔ ʌ ʃэ j͐ʃɜ ɭʃᴜ",
  // MAPO DE ARANIS • La tuta valo de supre
  // map = ʃᴜ j͐ʃɹ ı],ᴜ • of(SER,vowel) = j͑ʃɔƣ̋ • Aranis = ꞁȷ̀ᴜƣ̋ ꞁȷ̀ᴜ }ʃꞇɔ˞
  // tuta = ꞁȷ̀ɔ ɽ͑ʃ'ɹ ֭ſɭᴜ • valo = j͐ʃɜ ɭʃᴜ • el( Loko ) = j͐ʃэ ɭl̀э • supro = j͑ʃɜ ſɭ,ᴜ
  "titoloMapo": "ʃᴜ j͐ʃɹ ı],ᴜ ʌ j͑ʃɔƣ̋ ꞁȷ̀ᴜƣ̋ ꞁȷ̀ᴜ }ʃꞇɔ˞",
  "subtitoloMapo": "ꞁȷ̀ɔ ɽ͑ʃ'ɹ ֭ſɭᴜ j͐ʃɜ ɭʃᴜ ʌ j͐ʃэ ɭl̀э j͑ʃɜ ſɭ,ᴜ",
  "actEliri": "j͑ʃwc̗ ɭʃᴜ • Esc",
  "eliriKanuo": "j͑ʃwc̗ ɭʃᴜ ʌ j͑ʃɹ ſɭᴜ ɭl̀ɹ",
  "regiloKanuo": "WASD • ſɭɹ j͑ʃɹ ſɭᴜ ɭl̀ɹ ʌ ſɭw ſ̀ȷᴜ",
  "eliri": "j͑ʃwc̗ ɭʃᴜ",
  "eniriKanuo": "ſɭw ſ̀ȷᴜ ʌ j͑ʃɹ ſɭᴜ ɭl̀ɹ",
  // Retilo ( multludado ) — tostoj
  "retiloAliĝis": "ſɭw ſ̀ȷᴜ ʌ ⺓ ʌ ꞁȷ̀ɔ ɽ͑ʃ'ɹ j͑ʃᴜꞇ ʌ ŋᷠᴜƴ ⟅",
  "retiloForiris": "j͑ʃwc̗ ɭʃᴜ ʌ ⺓ ʌ ꞁȷ̀ɔ ɽ͑ʃ'ɹ j͑ʃᴜꞇ ʌ ŋᷠᴜƴ ⟅",
  // Food action labels
  "actGusti": "ſ͔ɭɔȝ •",
  "actKuxi": "ſȷɔ˞ᴜ ɭʃᴜ",
  "actLevi": "j͑ʃᴜ ʃɜƽ",
  // Manĝaĵnomoj de la dosiero satalaj-konstruaĵoj.ts
  "manĝFok0": "ſȷɜƽ ꞁȷ̀ɹ ŋᷠᴜ j͑ʃᴜꞇ • ı],ꞇƽ", "manĝFok1": "ſȷɜƽ ꞁȷ̀ɹ ŋᷠᴜ j͑ʃᴜꞇ • ſ͕ɭᴜ ɭʃɹ ᶅſᴜ", "manĝFok2": "ſȷɜƽ ꞁȷ̀ɹ ŋᷠᴜ j͑ʃᴜꞇ • ɭʃɜͷ̗ ı],w",
  "manĝTla0": "ſ̀ȷᴜ ɭʃɹ ᶅſᴜ • ɭʃɜ ſɭɹ", "manĝTla1": "ſ̀ȷᴜ ɭʃɹ ᶅſᴜ • ɭʃɹƽ", "manĝTla2": "ſ̀ȷᴜ ɭʃɹ ᶅſᴜ • j͐ʃᴜ ŋᷠɹⰱ",
  // Gustotekstoj de la dosiero satalaj-konstruaĵoj.ts
  "manĝFok0Flavor": "ſᶘэ ꞁȷ̀ɹ ŋᷠᴜ j͑ʃᴜꞇ ｡ ı],ꞇƽ ⟅",
  "manĝFok1Flavor": "ſᶘᴜ ֭ſɭᴜͷ̗ ｡ ſ͕ɭᴜ ɭʃɹ ᶅſᴜ ⟅",
  "manĝFok2Flavor": "ſᶘᴜ ֭ſɭᴜͷ̗ ｡ ɭʃɜͷ̗ ı],w ｡ ſ͕ɭᴜ ɭʃɹ ᶅſᴜ ｡ ſ̀ȷɔ ı],ͷ̗ɔʞ ⟅",
  "manĝTla0Flavor": "ſᶘᴜ ֭ſɭᴜͷ̗ ｡ ſ̀ȷᴜ ſɭɔͷ̗ ｡ ſɭɜ ſᶘɹᶗ‹ ｡ ſᶘᴜ v ſ͔ɭɔ ſןɹ j͑ʃᴜꞇ ⟅",
  "manĝTla1Flavor": "ſᶘᴜ ֭ſɭᴜͷ̗ ｡ ɭʃɹƽ ｡ ſɟɔ ɭl̀ɹ ｡ ſɭɜ ſᶘɹᶗ‹ ｡ ſᶘᴜ v ſ͔ɭɔ ſןɹ j͑ʃᴜꞇ ⟅",
  "manĝTla2Flavor": "ſᶘᴜ ֭ſɭᴜͷ̗ ｡ ſɭᶗ‹ɹ j͐ʃᴜ ŋᷠɹⰱ ｡ ſɭɜ ſᶘɹᶗ‹ ｡ ſɟɔ ɭl̀ɹ v ֭ſɭᴜ }ʃɔ j͑ʃᴜꞇ ( ſᶘᴜ j͑ʃͷ̗ᴜʞ ꞁȷ̀ᴜꞇ ) ⟅",
  // Pussxlefo-beroj — la nomo kombinas la ber-vorton kaj la plant-nomon.
  "manĝPuss0": "ſןꞇƽ j͑ʃɔ ſ̀ȷɔ ı],ͷ̗ɔʞ ſןɹɔ˞ ꞁȷ̀ᴜꞇ",
  "manĝPuss0Flavor": "ſᶘᴜ j͑ʃᴜꞇ ʌ j͐ʃᴜ ſɟɹ ⟅ ſɭɔ˞ɜƴ ʌ ſɭᴜ j͑ʃᴜ ʌ ı],ꞇͷ̗ ⟅",
  // Konstrua karto-labeletoj el satalaj-konstruaĵoj.ts TIPARO
  "tipDomo": "ſɭᴜ ſןɹ",
  "tipMangxejo": "ſɭᴜ ſ͔ɭɔȝ",
  "tipKasafeo": "ſɭᴜ j͑ʃᴜ ſȷɔ",
  "tipStacioxipo": "ſɭᴜ ſɭˬᴜ j͑ʃɔ ı],ᴜƴ",
  "tipTuro": "ſןᴜȝ ᶅſw ſɭɹ",
  "tipSanktejo": "j͑ʃɜ j͑ʃƨɹ",
  // Konstruaĵkarta flava teksto — ʌ apartigas kompletajn vortojn; spacoj interne
  // vortaraj kunmetaĵoj restas ordinaraj silabaj apartigiloj.
  "flvDomo": "j͑ʃᴜ j͑ʃ'ɔ ſɭᴜ ſןɹ ⟅",
  "flvMangxejo": "ꞁȷ̀ɹ ſɭꞇ ʌ ꞁȷ̀ᴜ ɽ͑ʃ'ᴜȝ ʌ j͑ʃᴜ ſ͔ɭɔȝ ⟅",
  "flvKasafeo": "j͑ʃᴜ ſɭɔ˞w j͐ʃ ʌ j͑ʃᴜ j͑ʃᴜ ſȷɔ ʌ ꞁȷ̀ᴜ ɽ͑ʃ'ᴜȝ ⟅",
  "flvStacioxipo": "j͑ʃᴜ ı],ᴜ ɽ͑ʃ'ᴜȝ ʌ ꞁȷ̀ᴜ ɽ͑ʃ'ᴜȝ ⟅",
  "flvTuro": "ᶅſw ſɭɹ ʌ ſןᴜȝ ⟅",
  "flvSanktejo": "j͑ʃɜ j͑ʃƨɹ ⟅",
  // Karto-statistikaj labeletoj el sperto.ts
  "statTieroj": "ɭʃᴜ }ʃɔƽ",
  "statDiamanto": "ſɟꞇȝ ſɭᴜⰱ",
  "statJes": "ſɭɹ ֭ſɭɹ",
  "statNe": "ſɟɔ ֭ſɭɹ",
  "statTipo": "֭ſɭᴜ ı],ɔ",
  "statPozicio": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜȝ",
  // WebGL-eraro el scena.ts
  "webglMesagxo": "ſ͕ȷɜ ſɭɹ ɽ͑ʃ'ɔ ʌ WebGL ⟅",
  "webglDetalo": "ɭʃɔ ſ͕ɭᴜƴ ʌ WebGL ⟅ j͑ʃɹƣ̋ ꞁȷ̀ɜ j͐ʃɹ ŋᷠꞇ ʌ ſɟᴜ ֭ſɭᴜ ſȷᴜ v ſɭɹ ſןɹ ⟅",
  "webglReprovi": "ɭʃɜ ŋᷠэ",
  // aria-labeletoj el index.html kaj sperto.ts
  "ariaButKrepusko": "ſןw ſɭɜ ʃɔ j͑ʃƨꞇʞ",
  "ariaDuskRegilo": "ſןw ſɭɜ ʃɔ j͑ʃƨꞇʞ ʌ j͑ʃп́ɔ j͑ʃ'ɔ ŋᷠɹ",
  // Vetero — la kvar eblaj atmosferoj ( ſ͕ɭɹ ſᶘɜ )
  "ariaButVetero": "ſ͕ɭɹ ſᶘɜ",
  "veteroNebula": "ŋᷠᴜ ֭ſɭᴜ",
  "veteroPluva": "֭ſɭᴜ ɭʃᴜ",
  "veteroHajla": "ſɭᴜ ɭʃᴜƽ",
  "veteroNega": "ſᶘᴜ ſȷᴜ",
  "ariaButPromeni": "ſɭᴜ ɭʃᴜ",
  "ariaButBruo": "ſȷᴜ ŋᷠᴜʞ",
  "ariaButOrbiti": "֭ſɭɹ j͑ʃɔ",
  "ariaButLingvo": "ſ͔ɭᴜ ᶅſɔ",
  "ariaSupermetaFermi": "}ʃɔƣ̋ ꞁȷ̀ᴜ ſ̀ȷɔ",
  // Informo-panelo — tradukoj poste ( lasita malplena )
  "ariaInformButono": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜ j͑ʃ'ɜ ſןɹ",
  "titoloInformo": "ꞁȷ̀ᴜ ɽ͑ʃ'ᴜ j͑ʃ'ɜ ſןɹ",
  "subtitoloInformo": "ſןᴜȝ • ŋᷠɜⅎᶗ‹ • ɭ(ᴜͷ̗",
  "tabKonstruajxoj": "ſןᴜȝ",
  "tabMangxajxoj": "ŋᷠɜⅎᶗ‹",
  "tabSpecioj": "ɭ(ᴜͷ̗",
  // Vestaro-langetoj — vortaraj vortoj ( j͑ʃɜȝ ɭʃɔ = vestoj, ſᶘᴜȝ = haroj )
  "taboVestoj": "j͑ʃɜȝ ɭʃɔ",
  "taboHararo": "ſᶘᴜȝ",
  // Bestoj kaj plantoj de la valo — konservativaj, dictionary-kontrolitaj
  // priskriboj. ʌ disigas kompletajn vortojn; prefiksoj restas kun la bazo.
  "grupoBesto": "ſןᴜ ſ͔ɭᴜ",
  "grupoPlanto": "ı],ᴜ ſ̀ȷɔ",
  "specBeroe": "j͐ʃɹᶗ‹ ſɭw ſןwƽ ꞁȷ̀ᴜꞇ",
  "flvSpecBeroe": "j͐ʃᴜ ֭ſɭᴜƽ ʌ j͐ʃɹᶗ‹",
  "specMnemiopsis": "j͐ʃɹᶗ‹ ſɟᴜ ı],ͷ̗ɔʞ ꞁȷ̀ᴜꞇ",
  "flvSpecMnemiopsis": "ı],ɔ ſɭw ı],ᴜ ʌ j͐ʃɹᶗ‹",
  "specPleŭrobrakia": "j͐ʃɹᶗ‹ j͐ʃᴜ ſןw ֭ſɭᴜ j͑ʃᴜꞇ",
  "flvSpecPleŭrobrakia": "j͑ʃɹ j͐ʃɹᶗ‹",
  "specGlacifiso": "ſ͕ɭᴜ ɭʃɹ ᶅſᴜ",
  "flvSpecGlacifiso": "ᶅſɹ ʌ ſɭᴜ",
  "specMarlaraksxo": "ɭʃɜͷ̗ ı],w",
  "flvSpecMarlaraksxo": "j͑ʃɹ ɭʃɜͷ̗ ı],w",
  // Neĝopetrelo ( ɭʃɔ ŋᷠɔƽ / Pagodroma nivea )
  "specNeĝopetrelo": "ɭʃɔ ŋᷠɔƽ",
  "flvSpecNeĝopetrelo": "}ʃɹ ɭʃᴜ j͑ʃɔ ʌ ſɭэ j͑ʃꞇ j͐ʃ ʌ ı],ᴜ }ʃᴜ j͑ʃᴜꞇ ʌ j͑ʃп́ɔ ᶅſɔ ֭ſɭɹ ʌ ſɭэ ſɭɔ ⟅",
  "specBetulo": "j͐ʃᴜ ŋᷠɹⰱ",
  "flvSpecBetulo": "ſ͔ɭэ ʌ ſɭɔ ֭ſɭw ʌ ſɟɔ ⟅",
  "specLariko": "ɭʃᴜ ſɭɔ˞ᴜͷ̗",
  "flvSpecLariko": "ſɟꞇ ʌ j͑ʃͷ̗ᴜʞ ʌ ſɟɔ ⟅",
  "specHxsxaksxlefo": "ſ̀ȷɔ ı],ͷ̗ɔʞ ֭ſɭᶗ‹ᴜƽ ꞁȷ̀ᴜꞇ",
  "flvSpecHxsxaksxlefo": "֭ſɭᶗ‹ᴜƽ ꞁȷ̀ᴜꞇ ʌ ſ̀ȷɔ ı],ͷ̗ɔʞ ⟅ ꞁȷ̀ɜ j͑ʃ'ᴜ ſᶘᴜ ֭ſɭᴜͷ̗ ⟅",
  "specFiliko": "ı],ᴜ ʃꞇ",
  "flvSpecFiliko": "j͐ʃᴜ̩ᴜ ʌ ı],ᴜ ſ̀ȷɔ ʌ ɭl̀эƣ̋ ꞁȷ̀ɜƴ ⟅",
  "specPurpuraFiliko": "ſ̀ȷɔ ı],ͷ̗ɔʞ ı],ᴜ ʃꞇ j͑ʃᴜꞇ",
  "flvSpecPurpuraFiliko": "ı],ɔ ſɭᴜȝ ʌ ı],ᴜ ʃꞇ j͐ʃ ʌ ꞁȷ̀ɜ ʃэ ᶅſw ſɭɹ ʌ ſ̀ȷɔ ı],ͷ̗ɔʞ ⟅",
  "specLikeno": "ꞁȷ̀ɹ ŋᷠᴜ",
  "flvSpecLikeno": "ſᶘᴜ ſ̀ȷɔ ｡ ꞁȷ̀э ſᶘw ⟅ ꞁȷ̀ɹ ŋᷠᴜ j͑ʃɔ ⟅",
  "specHerbo": "ſȷɔ ſᶘᴜʞ",
  "flvSpecHerbo": "ı],ɔ ſɭᴜȝ ʌ ſȷɔ ſᶘᴜʞ ʌ ֭ſɭɜ ŋᷠᴜ ʌ ı],ᴜ ſ̀ȷɔ ⟅",
  "specMusko": "ſɟэᶗ‹",
  "flvSpecMusko": "ꞁȷ̀ᴜ ſ̀ȷɔƽ ʌ j͐ʃэ j͑ʃɔ ı],ᴜ ſ̀ȷɔ ⟅",
  "specCetkuo": "ſᶘɔ ɭʃƽɹ",
  "flvSpecCetkuo": "ſȷɹʞ ʌ ı],ᴜ ſ̀ȷɔ ⟅",
  "specCakeo": "ſᶘᴜ ſɭɔ",
  "flvSpecCakeo": "ı],ɔ ſɭᴜȝ ʌ }ʃᴜ ɽ͑ʃ'ɹ j͑ʃᴜ ʌ ı],ᴜ ſ̀ȷɔ ⟅",
  "specPussxlefo": "ſ̀ȷɔ ı],ͷ̗ɔʞ ſןɹɔ˞ ꞁȷ̀ᴜꞇ",
  "flvSpecPussxlefo": "ŋᷠɜ ı],ᴜ ſ̀ȷɔ j͑ʃᴜꞇ j͑ʃ ʌ ı],ɔ ſɭᴜȝ ʌ ı],ᴜ ʃꞇ ʌ j͑ʃп́ɔ ſןᴜ j͐ʃэ ʌ ſ̀ȷɔ ı],ͷ̗ɔʞ ʌ ꞁȷ̀ɹ ſןꞇƽ ⟅",
  "ariaTrako0": "j͑ʃw ſɭʞɹȝ ı ſןw ſןᴜɔ˞ ɭʃꞇʞ ᶅſɔ",
  "ariaTrako1": "j͑ʃw ſɭʞɹȝ ɿ ſןᴜ ʃɜƽ ſ͔ɭɹ",
  "ariaTrako2": "j͑ʃw ſɭʞɹȝ ц ɭʃэʞ ɭʃꞇʞ",
  "ariaTrako3": "j͑ʃw ſɭʞɹȝ э j͐ʃɜ ɭʃᴜ ſɭᴜͷ̗ ɭʃɜ ı],ɔƽ",
  // Canvas alt text
  // Vesta nomoj ( custom names )
  "vestoVerdant": "j͐ʃᴜ̩ᴜ",
  "vestoHearth": "ſ̀ȷwɔ˞",
  "vestoMist": "ſ͔ɭэ",
  "vestoEmber": "ᶅſɔ j͐ʃᴜ",
  "vestoAzure": "ſɟɹ j͑ʃɹƽ",
  "vestoViolet": "ſᶘꞇ }ʃɔ",
  "vestoGilt": "ſɟꞇ",
  "vestoRose": "ᶅſɔ j͐ʃᴜ ſ͔ɭэ",
  "vestoObsidian": "֭ſɭw }ʃᴜ",
  "vestoCyan": "ꞁȷ̀ꞇ j͑ʃɔⅎᶗ‹",
  // Har-stiloj ( komponitaj el vortaraj vortoj )
  "sekcioHararo": "ſᶘᴜȝ ʌ j͑ʃп́ɔ ֭ſɭᴜ ı],ɔ",
  "haroMalalta": "ſɟɹ }ʃᴜ ſᶘᴜȝ",
  "haroLonga": "j͑ʃᴜʞ",
  // Har-koloroj ( vortaraj kolor-vortoj )
  "sekcioHarKoloroj": "ſᶘᴜȝ ʌ j͑ʃп́ɔ ᶅſɔ ֭ſɭɹ",
  "harKoloroBruna": "ſ̀ȷwɔ˞",
  "harKoloroNigra": "֭ſɭw }ʃᴜ j͑ʃᴜꞇ",
  "harKoloroRuĝeta": "ᶅſɔ j͐ʃᴜ ſ̀ȷwɔ˞",
  "harKoloroKaŝtana": "ſɭɜᴜ̩ ſɭэ",
  "harKoloroBlonda": "ſɟꞇ",
  "harKoloroGriza": "֭ſɭwƽ",
  // Konstruaj nomoj el realaj Iikrhiaj vortaraj vortoj ( Gawekiif )
  "paq0": "ꞁȷ̀ᴜƣ̋ ꞁȷ̀ꞇ ŋᷠᴜ }ʃɹ",
  "paq1": "ſɭᴜ ſןɹ",
  "paq2": "ſɭᴜ ᶅſw ſɭɹ",
  "paq3": "ſɭэᴜ̩ ſןɹ",
  "paq4": "ſɭɔⰱ",
  "paq5": "ſɟɹƽ ꞁȷ̀ᴜ }ʃw",
  "paq6": "ɭʃэ ſɭɔȝ",
  "paq7": "ſɟꞇȝ",
  "paq8": "ſɭᴜ ſɟɔ",
  "paq9": "ſȷɹ ŋᷠɹ",
  "paq10": "֭ſɭɹɔ˞",
  "paq11": "ı],ᴜȝ",
  "paq12": "ŋᷠᴜ ֭ſɭᴜ",
  "paq13": "ſᶘꞇ ɭl̀ɔ",
  "paq14": "ɭl̀ᴜ ſ͕ɭɜ",
  "paq15": "j͐ʃᴜ ŋᷠɹⰱ",
  "paq16": "j͑ʃɹ ı],w",
  "paq17": "ſɭэ j͑ʃꞇ",
  "paq18": "j͑ʃɜ ſᶘɹ",
  "paq19": "ſɭɔ }ʃɔ ı],ɜ",
  "paq20": "ſɭɹⰱ",
  "paq21": "ſ͔ɭɹ ɭʃɔ",
  "paq22": "ſɟᴜ ſᶘɔ ɭl̀ɹȝ",
  "paq23": "ſȷwɔ˞",
  "paq24": "ſɟᴜ j͑ʃɜȝ ɭʃɔ",
  "paq25": "ŋᷠɔ ſ̀ȷɔʞ",
  "paq26": "ᶅſɜ ſ͔ɭɜͷ̗",
  "paq27": "ſɭɔ j͐ʃc̭ᴜ",
  "paq28": "}ʃɜ ſɭɜƴ",
  "paq29": "ɭ(ɜ ŋᷠɜ ı],ᴜ",
  "paq30": "ɭ(ɜ ŋᷠɜ ſȷɔ",
  "paq31": "ſɭᴜɘ ꞁȷ̀ᴜ ſɟɔ",
  "paq32": "ſɭᴜ ɭ(ᴜͷ̗",
  "paq33": "ſɭᴜ ſɭˬᴜ j͑ʃɔ ı],ᴜƴ",
  // Trakonomoj ( trakoN ). Derivitaj de la aih-a Gawekiif per la sonaj reguloj.
  "muziko": "j͑ʃп́ꞇ ſɭɔƴ",
  "trako0": "ſןw ſןᴜɔ˞ ɭʃꞇʞ ᶅſɔ",
  "trako1": "ſןᴜ ʃɜƽ ſ͔ɭɹ",
  "trako2": "ſɭэ j͐ʃᴜ j͑ʃƨꞇʞ",
  "trako3": "j͐ʃɜ ɭʃᴜ ſɭᴜͷ̗ ɭʃɜ ı],ɔƽ",
};
