// ≺⧼ Tradukoj — la angla 🗣️ ⧽≻
// La anglaj tekstoj de la tuta interfaco.
// La vortaro estas nur datumoj — la funkcioj logxas en tradukoj.ts.

export const EN: Record<string, string> = {
  // Ĝustaj anglaj tradukoj por ĉiuj UI-ŝnuroj
  // Fonetaj transskriboj ( de aih ) uzataj nur por kutimaj nomoj ( vesto * )
  "titoloAranis": "Aranis",
  "subtitoloUrbo": "Khiss Lhota • Lhammithai Kayitteh",
  "eniri": "Enter",
  "butonoPromeni": "Walk",
  "butonoOrbiti": "Orbit",
  "butonoVestaro": "Wardrobe",
  "butonoHelpo": "Help",
  "titoloTeksilo": "Loom",
  "subtitoloTeksilo": "Long shirts • Short sleeves • Main and accent",
  "titoloSxargxo": "Aranis",
  "sxargxaSubskribo": "Loading",
  "sxargxaSatalo": "Constructing satals",
  "sxargxaTraboj": "Lifting beams",
  "sxargxaNebulo": "Mist flows through the valley",
  "kompasoNordo": "N",
  "regiloOrbito": "Orbit • Drag to look • Click for notes",
  "regiloPromeno": "Walk • WASD to move • Shift to run • Space to jump",
  "regiloMovado": "WASD to move • Fast walk",
  "regiloEniri": "E to interact • Enter building",
  "regiloMapo": "M for map",
  "regiloEliri": "Esc to exit",
  "regiloSpajroj": "Click to read notes",
  "regiloVesto": "Wardrobe",
  "titoloVojoj": "Paths",
  "subtitoloHelpo": "City notes",
  "titoloMapo": "Aranis Map",
  "subtitoloMapo": "The whole valley from above",
  "actEliri": "Esc • Exit",
  "eliriKanuo": "Exit canoe",
  "regiloKanuo": "WASD to steer",
  "eliri": "Exit",
  "eniriKanuo": "Enter canoe",
  // Retilo ( multludado ) — tostoj
  "retiloAliĝis": "Someone joined.",
  "retiloForiris": "Someone left.",
  // Food action labels
  "actGusti": "Taste •",
  "actKuxi": "Lie down",
  "actLevi": "Get up",
  // Manĝaĵnomoj de la dosiero satalaj-konstruaĵoj.ts
  // ( derivitaj de la aih-a Gawekiif per la sonaj reguloj )
  // Gustotekstoj de la dosiero satalaj-konstruaĵoj.ts
  "manĝFok0Flavor": "Lichen bread with duck baozi.",
  "manĝFok1Flavor": "Tsahal vinegar and icefish.",
  "manĝFok2Flavor": "Tsahal vinegar, sea spider, icefish, and shlef.",
  "manĝTla0Flavor": "Vinegar, milk, mint, and sparkling water.",
  "manĝTla1Flavor": "Vinegar, chili, yuzu, mint, and sparkling water.",
  "manĝTla2Flavor": "Vinegar, birch sap, mint, and bergamot tea.",
  "manĝPuss0": "Shlef Piisu berry",
  "manĝPuss0Flavor": "A cool, watery pop with a faint sweet aftertaste.",
  // Konstruaĵkartaj etikedoj
  // Konstruaĵkarta flava teksto
  "flvDomo": "Domo.",
  "flvMangxejo": "Komuna manĝejo.",
  "flvKasafeo": "Kunvenejo.",
  "flvStacioxipo": "Stacio.",
  "flvTuro": "Nubskrapulo.",
  "flvSanktejo": "Centro.",
  // Card stats
  "statTieroj": "Layers",
  "statDiamanto": "Diamond",
  "statJes": "Yes",
  "statNe": "No",
  "statTipo": "Type",
  "statPozicio": "Position",
  // WebGL error
  "webglMesagxo": "Your browser does not support WebGL. Update your browser for the full experience.",
  "webglDetalo": "Aranis requires WebGL to run. Please update your browser or check your GPU settings.",
  "webglReprovi": "Retry",
  // Aria labels
  "ariaButPromeni": "Walk",
  "ariaButBruo": "Background noise",
  "ariaButOrbiti": "Orbit",
  "ariaButLingvo": "Language",
  "ariaSupermetaFermi": "Close",
  // Information panel ( buildings • food • species )
  "ariaInformButono": "Information",
  "titoloInformo": "Aravopii",
  "subtitoloInformo": "Buildings • Food • Species",
  "tabKonstruajxoj": "Buildings",
  "tabMangxajxoj": "Food",
  "tabSpecioj": "Species",
  // Wardrobe tabs
  "taboVestoj": "Clothing",
  "taboHararo": "Hair",
  // La bestoj kaj plantoj de la valo ( el bestoj.ts kaj vegetajxo/ )
  "grupoBesto": "Animal",
  "grupoPlanto": "Plant",
  "specBeroe": "Beroe",
  "flvSpecBeroe": "An elongate comb jelly with eight comb rows.",
  "specMnemiopsis": "Mnemiopsis",
  "flvSpecMnemiopsis": "A round comb jelly with four oral lobes.",
  "specPleŭrobrakia": "Pleurobrachia",
  "flvSpecPleŭrobrakia": "A small round comb jelly with two long palps.",
  "specGlacifiso": "Icefish",
  "flvSpecGlacifiso": "A nearly transparent fish without hemoglobin.",
  "specMarlaraksxo": "Sea spider",
  "flvSpecMarlaraksxo": "A tiny sea spider with eight long legs.",
  "specNeĝopetrelo": "Snow petrel",
  "flvSpecNeĝopetrelo": "A pure white seabird gliding over the lake and the river.",
  "specBetulo": "Birch",
  "flvSpecBetulo": "A tree with white wood.",
  "specLariko": "Alpine larch",
  "flvSpecLariko": "The alpine larch ( Larix lyallii ) — a small montane conifer that drops its needles and turns gold in autumn.",
  "specHxsxaksxlefo": "Shlef Hshaku",
  "flvSpecHxsxaksxlefo": "A purple lettuce tree with curled leaves. Used to make vinegar.",
  "specFiliko": "Fern",
  "flvSpecFiliko": "A green plant on the forest floor.",
  "specPurpuraFiliko": "Shlef Shawhisu",
  "flvSpecPurpuraFiliko": "A tall purple fern that grows into a large tree.",
  "specLikeno": "Lichen",
  "flvSpecLikeno": "Algae and fungus. Iimase.",
  "specHerbo": "Grass",
  "flvSpecHerbo": "Grass like a cyan plant.",
  "specMusko": "Moss",
  "flvSpecMusko": "A mound that is actually a plant.",
  "specCetkuo": "Tsetkih",
  "flvSpecCetkuo": "A tall unbranched scouring rush with strobili.",
  "specCakeo": "Tsakeh",
  "flvSpecCakeo": "Great branch-whorled horsetails at the lakeshore.",
  "specPussxlefo": "Shlef Piisu",
  "flvSpecPussxlefo": "A fern-sized purple lettuce plant with transparent edible berries.",
  // Aria-labeleto por la krepuska baskulo
  "ariaButKrepusko": "Dusk",
  "ariaDuskRegilo": "Dusk level",
  // Vetero — la kvar eblaj atmosferoj
  "ariaButVetero": "Weather",
  "veteroNebula": "Foggy",
  "veteroPluva": "Rainy",
  "veteroHajla": "Hail",
  "veteroNega": "Snowy",
  // ariaTrakoN. Derivitaj ( prefikso + derivita trakonomo )
  // Canvas alt text
  // Clothing names
  "vestoVerdant": "Green",
  "vestoHearth": "Brown",
  "vestoMist": "White",
  "vestoEmber": "Red",
  "vestoAzure": "Blue",
  "vestoViolet": "Purple",
  "vestoGilt": "Yellow",
  "vestoRose": "Pink",
  "vestoObsidian": "Black",
  "vestoCyan": "Cyan",
  // Hair styles
  "sekcioHararo": "Hair styles",
  "haroMalalta": "Short",
  "haroLonga": "Long",
  // Hair colors
  "sekcioHarKoloroj": "Hair colors",
  "harKoloroBruna": "Brown",
  "harKoloroNigra": "Black",
  "harKoloroRuĝeta": "Auburn",
  "harKoloroKaŝtana": "Chestnut",
  "harKoloroBlonda": "Blonde",
  "harKoloroGriza": "Gray",
  // Konstruaĵnomoj ( en )
  "muziko": "Music",
};
