// ≺⧼ ការបកប្រែ , ភាសាអេស្ពេរ៉ង់តូ 🗣️ ⧽≻

export const EO: Record<string, string> = {
  "titoloAranis": "Aranis",
  "subtitoloUrbo": "Ĥusa Lotao • Lamuza Kajteo",
  "eniri": "Eniri",
  "butonoPromeni": "PROMENI",
  "butonoOrbiti": "ORBITI",
  "butonoVestaro": "VESTARO",
  "butonoHelpo": "Helpo",
  "titoloTeksilo": "Teksilo",
  "subtitoloTeksilo": "Longaj ĉemizoj • mallongaj manikoj • ĉefa kaj akcenta",
  "titoloSxargxo": "Araniso",
  "sxargxaSubskribo": "Ŝargado...",
  "sxargxaSatalo": "Konstruado de satalaĵoj",
  "sxargxaTraboj": "Levado de traboj",
  "sxargxaNebulo": "Nebulo fluas tra la valo",
  "kompasoNordo": "N",
  "regiloOrbito": "Orbito • trenu por rigardi • alklaku por notoj",
  "regiloPromeno": "Promeni • WASD moviĝi • Shift por kuri • Spaco por salti",
  "regiloMovado": "WASD moviĝi • rapida piedo",
  "regiloEniri": "E por interagi • eniri konstruaĵon",
  "regiloMapo": "M por mapo",
  "regiloEliri": "Esc por eliri",
  "regiloSpajroj": "Alklaku por legi notojn",
  "regiloVesto": "Vestaro",
  "titoloVojoj": "Vojoj",
  "subtitoloHelpo": "Notoj pri la urbo",
  "titoloMapo": "Mapo de Araniso",
  "subtitoloMapo": "La tuta valo de supre",
  "actEliri": "Esc • Eliri",
  "eliriKanuo": "Eliri kanuon",
  "regiloKanuo": "WASD por direkti",
  "eliri": "Eliri",
  "eniriKanuo": "Eniri kanuon",
  "retiloAliĝis": "Iu aliĝis.",
  "retiloForiris": "Iu foriris.",
  "actGusti": "Guŝu •",
  "actKuxi": "Kuŝi",
  "actLevi": "Levi",
  "manĝFok0Flavor": "Pano el likeno kun anasa baozi.",
  "manĝFok1Flavor": "Tsahal-vinagro kaj glacifiŝo.",
  "manĝFok2Flavor": "Tsahal-vinagro, mara araneo, glacifiŝo kaj ŝlefo.",
  "manĝTla0Flavor": "Vinagro, lakto, mento kaj ŝaŭmakvo.",
  "manĝTla1Flavor": "Vinagro, kapsiko, juzuo, mento kaj ŝaŭmakvo.",
  "manĝTla2Flavor": "Vinagro, betula suko, mento kaj bergamota teo.",
  "manĝPuss0": "Pusŝlefo-bero",
  "manĝPuss0Flavor": "Malvarmeta, akva krispo kun sukereta postgusto.",
  "flvDomo": "Domo.",
  "flvMangxejo": "Komuna manĝejo.",
  "flvKasafeo": "Kunvenejo.",
  "flvStacioxipo": "Stacio.",
  "flvTuro": "Nubskrapulo.",
  "flvSanktejo": "Centro.",
  "statTieroj": "Tavoloj",
  "statDiamanto": "Diamanto",
  "statJes": "Jes",
  "statNe": "Ne",
  "statTipo": "Tipo",
  "statPozicio": "Pozicio",
  "webglMesagxo": "Via retumilo ne subtenas WebGL. Ĝisdatigu vian retumilon por sperti la plenan sperton.",
  "webglDetalo": "Araniso postulas WebGL por funkcii. Ĝisdatigu vian retumilon aŭ kontrolu viajn GPU-agordojn.",
  "webglReprovi": "Reprovi",
  "ariaButPromeni": "Promeni",
  "ariaButBruo": "Fona bruo",
  "ariaButOrbiti": "Orbito",
  "ariaButLingvo": "Ŝanĝi la lingvon de la urbo",
  "ariaSupermetaFermi": "Fermi",
  "ariaInformButono": "Malfermi informojn",
  "titoloInformo": "Arazopuo",
  "subtitoloInformo": "Konstruaĵoj • manĝaĵoj • specioj",
  "tabKonstruajxoj": "Konstruaĵoj",
  "tabMangxajxoj": "Manĝaĵoj",
  "tabSpecioj": "Specioj",
  "taboVestoj": "Vestoj",
  "taboHararo": "Hararo",
  "grupoBesto": "Besto",
  "grupoPlanto": "Planto",
  "specBeroe": "Beroo",
  "flvSpecBeroe": "Longforma kombomeduzo kun ok kombovicoj.",
  "specMnemiopsis": "Mnemiopsiso",
  "flvSpecMnemiopsis": "Ronda kombomeduzo kun kvar buŝaj loboj.",
  "specPleŭrobrakia": "Pleŭrobrakio",
  "flvSpecPleŭrobrakia": "Malgranda ronda kombomeduzo kun du longaj palpoj.",
  "specGlacifiso": "Glacifiso",
  "flvSpecGlacifiso": "Preskaŭ travidebla fiŝo sen hemoglobino.",
  "specMarlaraksxo": "Marlaraksxo",
  "flvSpecMarlaraksxo": "Eta mararaneo kun ok longegaj kruroj.",
  "specNeĝopetrelo": "Neĝopetrelo",
  "flvSpecNeĝopetrelo": "Pura blanka marbirdo glitanta super la lago kaj la rivero.",
  "specBetulo": "Betulo",
  "flvSpecBetulo": "Arbo kun blanka ligno.",
  "specLariko": "Alpa lariko",
  "flvSpecLariko": "La alpa lariko ( Larix lyallii ) — malgranda alpina konifero, kiu perdas siajn pinglojn aŭtune kaj orflaviĝas.",
  "specHxsxaksxlefo": "Ĥŝakŝlefo",
  "flvSpecHxsxaksxlefo": "Purpura laktukarbo kun kurbaj folioj. Uzata por fari vinagron.",
  "specFiliko": "Filiko",
  "flvSpecFiliko": "Verda planto sur la arbara grundo.",
  "specPurpuraFiliko": "Ŝafiŝlefo",
  "flvSpecPurpuraFiliko": "Alta purpura filiko de la ekstera arbaro.",
  "specLikeno": "Likeno",
  "flvSpecLikeno": "Algoj kaj fungo. Iimase.",
  "specHerbo": "Herbo",
  "flvSpecHerbo": "Herbo simila al ciankolora planto.",
  "specMusko": "Musko",
  "flvSpecMusko": "Monteto, kiu fakte estas planto.",
  "specCetkuo": "Cetkuo",
  "flvSpecCetkuo": "Alta senbranĉa skurĝa kano kun strobiloj.",
  "specCakeo": "Cakeo",
  "flvSpecCakeo": "Granda branĉet-kirla ĉevalvosto ĉe la lagrando.",
  "specPussxlefo": "Pusŝlefo",
  "flvSpecPussxlefo": "Fern-granda purpura laktukplanto kun travideblaj manĝeblaj beroj.",
  "ariaButKrepusko": "Ŝalti krepuskan reĝimon",
  "ariaDuskRegilo": "Krepuska nivelo",
  "ariaButVetero": "Vetero",
  "veteroNebula": "Nebula",
  "veteroPluva": "Pluva",
  "veteroHajla": "Hajla",
  "veteroNega": "Neĝa",
  "vestoVerdant": "Verda",
  "vestoHearth": "Bruna",
  "vestoMist": "Blanka",
  "vestoEmber": "Ruĝa",
  "vestoAzure": "Blua",
  "vestoViolet": "Purpura",
  "vestoGilt": "Flava",
  "vestoRose": "Roza",
  "vestoObsidian": "Nigra",
  "vestoCyan": "Cejana",
  "sekcioHararo": "Harstiloj",
  "haroMalalta": "Mallonga",
  "haroLonga": "Longa",
  "sekcioHarKoloroj": "Har-koloroj",
  "harKoloroBruna": "Bruna",
  "harKoloroNigra": "Nigra",
  "harKoloroRuĝeta": "Ruĝeta",
  "harKoloroKaŝtana": "Kaŝtana",
  "harKoloroBlonda": "Blonda",
  "harKoloroGriza": "Griza",
  "muziko": "Muziko",
};
