// ≺⧼ Tradukoj — la japana 🗣️ ⧽≻
// La japanaj tekstoj de la tuta interfaco.
// La vortaro estas nur datumoj — la funkcioj logxas en tradukoj.ts.

export const JA: Record<string, string> = {
  // Ĝustaj japanaj tradukoj por ĉiuj UI-ŝnuroj
  // Fonetaj transskriboj ( de aih ) uzataj nur por kutimaj nomoj ( vesto * )
  "titoloAranis": "アラニス",
  "subtitoloUrbo": "ロタ・イーヒス • カジーテ・セラーミョヴ",
  "eniri": "入る",
  "butonoPromeni": "歩く",
  "butonoOrbiti": "周回",
  "butonoVestaro": "ワードローブ",
  "butonoHelpo": "ヘルプ",
  "titoloTeksilo": "ザ・ルーム",
  "subtitoloTeksilo": "長いシャツ • 短い袖 • メインとアクセント",
  "titoloSxargxo": "アラニス",
  "sxargxaSubskribo": "建設中…",
  "sxargxaSatalo": "サタルを建設中",
  "sxargxaTraboj": "梁を持ち上げ中",
  "sxargxaNebulo": "霧が谷を流れる",
  "kompasoNordo": "北",
  "regiloOrbito": "周回 • ドラッグして見る • クリックでノート",
  "regiloPromeno": "歩く • WASDで移動 • Shiftで走る • Spaceでジャンプ",
  "regiloMovado": "WASDで移動 • 早足",
  "regiloEniri": "Eで操作 • 建物に入る",
  "regiloMapo": "Mで地図",
  "regiloEliri": "Escで出る",
  "regiloSpajroj": "クリックでノートを読む",
  "regiloVesto": "ワードローブ",
  "titoloVojoj": "道",
  "subtitoloHelpo": "街のノート",
  "titoloMapo": "アラニスの地図",
  "subtitoloMapo": "谷全体を上から見る",
  "actEliri": "Esc • 出る",
  "eliriKanuo": "カヌーから出る",
  "regiloKanuo": "WASDで操縦",
  "eliri": "出る",
  "eniriKanuo": "カヌーに乗る",
  // Retilo ( multludado ) — tostoj
  "retiloAliĝis": "誰かが加わりました。",
  "retiloForiris": "誰かが去りました。",
  // Food action labels
  "actGusti": "味見 •",
  "actKuxi": "横になる",
  "actLevi": "起きる",
  // Manĝaĵnomoj de la dosiero satalaj-konstruaĵoj.ts
  // ( derivitaj de la aih-a Gawekiif per la sonaj reguloj )
  // Gustotekstoj de la dosiero satalaj-konstruaĵoj.ts
  "manĝFok0Flavor": "リケンパンの鴨入り包子。",
  "manĝFok1Flavor": "ツァハラ酢とアイスフィッシュ。",
  "manĝFok2Flavor": "ツァハラ酢、ウミグモ、アイスフィッシュ、シュレフ。",
  "manĝTla0Flavor": "酢、牛乳、ミント、炭酸水。",
  "manĝTla1Flavor": "酢、唐辛子、柚子、ミント、炭酸水。",
  "manĝTla2Flavor": "酢、白樺樹液、ミント、ベルガモット茶。",
  "manĝPuss0Flavor": "ひんやりと水気のある食感で、ほのかに甘い。",
  // Konstruaĵkartaj etikedoj
  // Konstruaĵkarta flava teksto
  "flvDomo": "家。",
  "flvMangxejo": "共同の食事処。",
  "flvKasafeo": "会議室。",
  "flvStacioxipo": "駅。",
  "flvTuro": "超高層建築。",
  "flvSanktejo": "中心。",
  // Card stats
  "statTieroj": "階層",
  "statDiamanto": "ダイヤ",
  "statJes": "有",
  "statNe": "無",
  "statTipo": "種類",
  "statPozicio": "位置",
  // WebGL error
  "webglMesagxo": "お使いのブラウザはWebGLをサポートしていません。ブラウザを更新してください。",
  "webglDetalo": "アラニスはWebGLが必要です。ブラウザを更新するか、GPU設定を確認してください。",
  "webglReprovi": "再試行",
  // Aria labels
  "ariaButPromeni": "歩く",
  "ariaButBruo": "背景ノイズ",
  "ariaButOrbiti": "周回",
  "ariaButLingvo": "言語",
  "ariaSupermetaFermi": "閉じる",
  // 情報パネル ( 建物 • 食べ物 • 種族 )
  "ariaInformButono": "情報を開く",
  "titoloInformo": "情報",
  "subtitoloInformo": "建物 • 食べ物 • 種族",
  "tabKonstruajxoj": "建物",
  "tabMangxajxoj": "食べ物",
  "tabSpecioj": "種族",
  // ワードローブのタブ
  "taboVestoj": "服",
  "taboHararo": "髪",
  // 谷の動物と植物 ( bestoj.ts と vegetajxo/ から )
  "grupoBesto": "動物",
  "grupoPlanto": "植物",
  "specBeroe": "ベロー",
  "flvSpecBeroe": "細長い有櫛動物。八列の櫛を持つ。",
  "specMnemiopsis": "ネミオプシス",
  "flvSpecMnemiopsis": "四つの口葉を持つ丸い有櫛動物。",
  "specPleŭrobrakia": "プレウロブラキア",
  "flvSpecPleŭrobrakia": "二本の長い触手を持つ小さな丸い有櫛動物。",
  "specGlacifiso": "氷魚",
  "flvSpecGlacifiso": "ヘモグロビンを持たない、ほぼ透明な魚。",
  "specMarlaraksxo": "ウミグモ",
  "flvSpecMarlaraksxo": "八本の長い脚を持つ小さなウミグモ。",
  "specNeĝopetrelo": "ユキドリ",
  "flvSpecNeĝopetrelo": "湖と川の上を滑空する真っ白な海鳥。",
  "flvSpecBetulo": "白い木材を持つ木。",
  "flvSpecLariko": "秋に黄金色の針葉を持つ高山性の針葉樹。",
  "flvSpecHxsxaksxlefo": "紫色のレタスの木。巻いた葉を持ち、酢作りに使う。",
  "flvSpecFiliko": "森の地面に生える緑の植物。",
  "flvSpecPurpuraFiliko": "外側の森に生える高い紫色のシダ。",
  "flvSpecLikeno": "藻類と菌類。イマセ。",
  "flvSpecHerbo": "シアン色の植物のような草。",
  "flvSpecMusko": "実は植物である小山。",
  "flvSpecCetkuo": "胞子嚢を持つ、高く枝分かれしないトクサ。",
  "flvSpecCakeo": "湖岸に生える、大きく枝が輪生するトクサ。",
  "flvSpecPussxlefo": "シダほどの大きさの紫色のレタス植物。透き通った食べられる実をつける。",
  // Aria-labeleto por la krepuska baskulo
  "ariaButKrepusko": "夕暮れモードを切り替え",
  "ariaDuskRegilo": "夕暮れのレベル",
  // 天気 — 四つの可能な大気
  "ariaButVetero": "天気",
  "veteroNebula": "霧",
  "veteroPluva": "雨",
  "veteroHajla": "雹",
  "veteroNega": "雪",
  // ariaTrakoN. Derivitaj ( prefikso + derivita trakonomo )
  // Canvas alt text
  // Clothing names
  "vestoVerdant": "緑",
  "vestoHearth": "茶色",
  "vestoMist": "白",
  "vestoEmber": "赤",
  "vestoAzure": "青",
  "vestoViolet": "紫",
  "vestoGilt": "黄",
  "vestoRose": "桃色",
  "vestoObsidian": "黒",
  "vestoCyan": "シアン",
  // 髪型
  "sekcioHararo": "髪型",
  "haroMalalta": "ショート",
  "haroLonga": "ロング",
  // 髪の色
  "sekcioHarKoloroj": "髪の色",
  "harKoloroBruna": "茶色",
  "harKoloroNigra": "黒",
  "harKoloroRuĝeta": "赤茶",
  "harKoloroKaŝtana": "栗色",
  "harKoloroBlonda": "金髪",
  "harKoloroGriza": "グレー",
  // Konstruaĵnomoj ( paqN )
  "muziko": "音楽",
};
