// ≺⧼ Tradukoj — la kmerea 🗣️ ⧽≻
// La kmereaj ( Kambogxaj ) tekstoj de la tuta interfaco.
// La vortaro estas nur datumoj — la funkcioj logxas en tradukoj.ts.

export const KM: Record<string, string> = {
  // Kmeraj ( Kamboĝaj ) tradukoj por ĉiuj UI-ŝnuroj
  // Fonetaj proksimumoj en kmera skribo por kutimaj nomoj
  "titoloAranis": "អរ៉ានីស",
  "subtitoloUrbo": "ឡូតា-អ៊ីហ៊ីស • កាជីតេ-សេឡាមយ៉ូវ",
  "eniri": "ចូល",
  "butonoPromeni": "ដើរ",
  "butonoOrbiti": "ទស្សនា",
  "butonoVestaro": "សម្លៀកបំពាក់",
  "butonoHelpo": "ជំនួយ",
  "titoloTeksilo": "តម្បាញ",
  "subtitoloTeksilo": "អាវវែង • ដៃខ្លី • ពណ៌ចម្បង និង ពណ៌បន្ទាប់",
  "titoloSxargxo": "អរ៉ានីស",
  "sxargxaSubskribo": "កំពុងសាងសង់",
  "sxargxaSatalo": "ហ្សីហ្គូរ៉ាត់កំពុងឡើង",
  "sxargxaTraboj": "ធ្នឹមឈើកំពុងគ្រាំ",
  "sxargxaNebulo": "អ័ព្ទហូរកាត់ជ្រលង",
  "kompasoNordo": "ជ",
  "regiloOrbito": "ទស្សនា • អូសដើម្បីមើល • ចុចសម្រាប់កំណត់ត្រា",
  "regiloPromeno": "ដើរ • WASD ដើម្បីផ្លាស់ទី • Shift ដើម្បីរត់ • Space ដើម្បីលោត",
  "regiloMovado": "WASD ដើម្បីផ្លាស់ទី • ដើរលឿន",
  "regiloEniri": "E ដើម្បីចូល/ចេញ • ចូលអាគារ",
  "regiloMapo": "M សម្រាប់ផែនទី",
  "regiloEliri": "Escape ដើម្បីចេញ",
  "regiloSpajroj": "ចុចប៉មដើម្បីអានកំណត់ត្រា • ចូល",
  "regiloVesto": "សម្លៀកបំពាក់ • ប្តូរសំលៀកបំពាក់របស់អ្នក",
  "titoloVojoj": "ផ្លូវ",
  "subtitoloHelpo": "កំណត់ត្រាជំនួយអំពីទីក្រុង",
  "titoloMapo": "ផែនទីអារ៉ានីស",
  "subtitoloMapo": "ជ្រលងទាំងមូលពីលើ",
  "actEliri": "ចេញ • Esc",
  "eliriKanuo": "ដើម្បីចេញពីទូក",
  "regiloKanuo": "ការគ្រប់គ្រងទូក • WASD ដើម្បីបង្វែរ",
  "eliri": "ចេញ",
  "eniriKanuo": "ចូលទូក",
  // Retilo ( multludado ) — tostoj
  "retiloAliĝis": "នរណាម្នាក់បានចូលរួម។",
  "retiloForiris": "នរណាម្នាក់បានចាកចេញ។",
  // Food action labels
  "actGusti": "ភ្លក់ •",
  "actKuxi": "ដេក",
  "actLevi": "ក្រោក",
  // Manĝaĵnomoj de la dosiero satalaj-konstruaĵoj.ts
  // ( derivitaj de la aih-a Gawekiif per la sonaj reguloj )
  // Gustotekstoj de la dosiero satalaj-konstruaĵoj.ts
  "manĝFok0Flavor": "នំប៉័ងលីខេន មានប៉ាវសាច់ទាខាងក្នុង។",
  "manĝFok1Flavor": "ទឹកខ្មេះត្សាហាល និងត្រីទឹកកក។",
  "manĝFok2Flavor": "ទឹកខ្មេះត្សាហាល ពីងពាងសមុទ្រ ត្រីទឹកកក និងស្លេហ្វ។",
  "manĝTla0Flavor": "ទឹកខ្មេះ ទឹកដោះគោ ជីអង្កាម និងទឹកមានពពុះ។",
  "manĝTla1Flavor": "ទឹកខ្មេះ ម្ទេស យូស៊ុ ជីអង្កាម និងទឹកមានពពុះ។",
  "manĝTla2Flavor": "ទឹកខ្មេះ ទឹកប៊ីច ជីអង្កាម និងតែប៊ឺហ្គាម៉ុត។",
  "manĝPuss0Flavor": "ត្រជាក់ មានទឹក និងផ្អែមបន្តិច។",
  // Konstruaĵkartaj etikedoj
  // Konstruaĵkarta flava teksto
  "flvDomo": "ផ្ទះ។",
  "flvMangxejo": "កន្លែងបរិភោគអាហាររួម។",
  "flvKasafeo": "បន្ទប់ប្រជុំ។",
  "flvStacioxipo": "ស្ថានីយ។",
  "flvTuro": "អគារខ្ពស់។",
  "flvSanktejo": "មជ្ឈមណ្ឌល។",
  // Card stats
  "statTieroj": "ជាន់",
  "statDiamanto": "ពេជ្រ",
  "statJes": "បាទ",
  "statNe": "ទេ",
  "statTipo": "ប្រភេទ",
  "statPozicio": "ទីតាំង",
  // WebGL error
  "webglMesagxo": "កម្មវិធីរុករករបស់អ្នកមិនគាំទ្រ WebGL ទេ។ សូមធ្វើបច្ចុប្បន្នភាពកម្មវិធីរុករករបស់អ្នកសម្រាប់បទពិសោធន៍ពេញលេញ។",
  "webglDetalo": "អរ៉ានីស ត្រូវការ WebGL ដើម្បីដំណើរការ។ សូមធ្វើបច្ចុប្បន្នភាពកម្មវិធីរុករករបស់អ្នក ឬពិនិត្យការកំណត់ GPU របស់អ្នក។",
  "webglReprovi": "ព្យាយាមម្តងទៀត",
  // Aria labels
  "ariaButPromeni": "ដើរ",
  "ariaButBruo": "សំឡេងផ្ទៃខាងក្រោយ",
  "ariaButOrbiti": "ទស្សនា",
  "ariaButLingvo": "ភាសា",
  "ariaSupermetaFermi": "បិទ",
  // ផ្ទាំងព័ត៌មាន ( អាគារ • អាហារ • ប្រភេទ )
  "ariaInformButono": "បើកព័ត៌មាន",
  "titoloInformo": "ព័ត៌មាន",
  "subtitoloInformo": "អាគារ • អាហារ • ប្រភេទ",
  "tabKonstruajxoj": "អាគារ",
  "tabMangxajxoj": "អាហារ",
  "tabSpecioj": "ប្រភេទ",
  // ផ្ទាំងសម្លៀកបំពាក់
  "taboVestoj": "សម្លៀកបំពាក់",
  "taboHararo": "សក់",
  // សត្វ និងរុក្ខជាតិនៃជ្រលង ( ពី bestoj.ts និង vegetajxo/ )
  "grupoBesto": "សត្វ",
  "grupoPlanto": "រុក្ខជាតិ",
  "specBeroe": "បេរ៉ូ",
  "flvSpecBeroe": "ចាហួយសិតរាងវែង មានជួរសិតប្រាំបី។",
  "specMnemiopsis": "នេមីអូបស៊ីស",
  "flvSpecMnemiopsis": "ចាហួយសិតរាងមូល មានកំពូលមាត់បួន។",
  "specPleŭrobrakia": "ប្លឿរ៉ូប្រាគីអា",
  "flvSpecPleŭrobrakia": "ចាហួយសិតមូលតូច មានអង់តែនវែងពីរ។",
  "specGlacifiso": "ត្រីទឹកកក",
  "flvSpecGlacifiso": "ត្រីស្ទើរតែថ្លា ដែលគ្មានហេម៉ូក្លូប៊ីន។",
  "specMarlaraksxo": "ពីងពាងសមុទ្រ",
  "flvSpecMarlaraksxo": "ពីងពាងសមុទ្រតូច មានជើងវែងប្រាំបី។",
  "specNeĝopetrelo": "បក្សីព្រិល",
  "flvSpecNeĝopetrelo": "សត្វសមុទ្រពណ៌សសុទ្ធ ហើរពីលើបឹង និងទន្លេ។",
  "flvSpecBetulo": "ដើមឈើដែលមានឈើពណ៌ស។",
  "flvSpecLariko": "ដើមឈើម្ជុលភ្នំ មានម្ជុលពណ៌មាសនៅរដូវស្លឹកឈើជ្រុះ។",
  "flvSpecHxsxaksxlefo": "ដើមសាឡាត់ពណ៌ស្វាយ មានស្លឹករមួល ហើយប្រើធ្វើទឹកខ្មេះ។",
  "flvSpecFiliko": "រុក្ខជាតិពណ៌បៃតងដែលដុះលើដីព្រៃ។",
  "flvSpecPurpuraFiliko": "ហ្វឺនពណ៌ស្វាយខ្ពស់នៅព្រៃខាងក្រៅ។",
  "flvSpecLikeno": "សារាយ និងផ្សិត។ អ៊ីម៉ាសេ។",
  "flvSpecHerbo": "ស្មៅដូចជារុក្ខជាតិពណ៌ស៊ីយ៉ង់។",
  "flvSpecMusko": "គំនរដែលតាមពិតជារុក្ខជាតិ។",
  "flvSpecCetkuo": "រុក្ខជាតិខ្ពស់គ្មានមែក មានកោនគ្រាប់ពូជ។",
  "flvSpecCakeo": "រុក្ខជាតិខ្ពស់មានមែកជុំវិញ ដុះនៅមាត់បឹង។",
  "flvSpecPussxlefo": "រុក្ខជាតិសាឡាត់ពណ៌ស្វាយទំហំប៉ុនហ្វឺន មានផ្លែថ្លាដែលអាចបរិភោគបាន។",
  // Aria-labeleto por la krepuska baskulo
  "ariaButKrepusko": "ប្តូររបៀបព្រលប់",
  "ariaDuskRegilo": "កម្រិតព្រលប់",
  // អាកាសធាតុ — បរិយាកាសដែលអាចទាំងបួន
  "ariaButVetero": "អាកាសធាតុ",
  "veteroNebula": "អ័ព្ទ",
  "veteroPluva": "ភ្លៀង",
  "veteroHajla": "ព្រិលកក",
  "veteroNega": "ព្រិល",
  // ariaTrakoN. Derivitaj ( prefikso + derivita trakonomo )
  // Canvas alt text
  // Clothing names ( phonetic approximations in Khmer script )
  "vestoVerdant": "ពណ៌បៃតង",
  "vestoHearth": "ពណ៌ត្នោត",
  "vestoMist": "ពណ៌ស",
  "vestoEmber": "ពណ៌ក្រហម",
  "vestoAzure": "ពណ៌ខៀវ",
  "vestoViolet": "ពណ៌ស្វាយ",
  "vestoGilt": "ពណ៌លឿង",
  "vestoRose": "ពណ៌ផ្កាឈូក",
  "vestoObsidian": "ពណ៌ខ្មៅ",
  "vestoCyan": "ពណ៌ស៊ីអាន",
  // ម៉ូដសក់
  "sekcioHararo": "ម៉ូដសក់",
  "haroMalalta": "ខ្លី",
  "haroLonga": "វែង",
  // ពណ៌សក់
  "sekcioHarKoloroj": "ពណ៌សក់",
  "harKoloroBruna": "ត្នោត",
  "harKoloroNigra": "ខ្មៅ",
  "harKoloroRuĝeta": "ក្រហមឆ្អៅ",
  "harKoloroKaŝtana": "ដើមទ្រូង",
  "harKoloroBlonda": "ទង់ដែង",
  "harKoloroGriza": "ប្រផេះ",
  // Konstruaĵnomoj ( paqN )
  "muziko": "តន្ត្រី",
};
